#Đối với những config ko gợi ý thì là do tự config và nó dùng để khai báo biến trong file sys cho các class dùng
#config server tomcat
#Đây đc gọi là các thuộc tính config cho application
Server:
  port: 8081
  servlet:
#    Đây là prefix endpoint: nên springSecurityConfig chỉ cần config endpoint còn lại
    context-path: /springboot3
#config driver connect with mysql
spring:
  datasource:
    url: jdbc:mysql:    username: root
    password: 21102004
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
    signerKey: "vmVxExKB/L9vJUrgpZjRqtX3CEsrhXPi2rWsItm3vo2g2f2g0kacpffalZb2E62W"
    valid-duration: 3600 #seconds
    refreshable-duration: 36000  #seconds









